{
    "sddFormat": "sdd/table/object-of-arrays",
    "version": "1.0.0",
    "validation": "enforced",
    "definitions": {
        "contract_id_preferred": {
            "kind": "string"
            "optional": false
        },
        "contract no": {
            "kind": "string",
            "optional": false
        },
        "contract_no_preferred": {
            "kind": "string",
            "optional": false
        },
        "1st_source": {
            "kind": "string",
            "optional": false
        },
        "2nd_source": {
            "kind": "string",
            "optional": false
        },
        "scenario": {
            "kind": "string",
            "optional": false
        }
    },
    "data": {
        "contract_id_preferred": [
            "ENEOS DNC",
            "RGT GLNG",
            "RGT GLNG",
            "THG LNGC",
            "THG LNGC",
            "THG PF",
            "THG PF",
            "THG Bintulu 2",
            "THG Bintulu 2",
            "RGT BLNG",
            "THG Bintulu 2",
            "THG Bintulu 1",
            "THG IND",
            "THE DNC",
            "TG SATU NEW",
            "TG SATU NEW",
            "TG SATU NEW",
            "TG SATU NEW",
            "TG SATU NEW",
            "THG Bintulu 1",
            "TG DNC",
            "RGT PEGT",
            "RGT PEGT",
            "BP MCN DES",
            "BP MCN DES",
            "KOMIPO",
            "Vitol LNGC DES",
            "Vitol LNGC DES",
            "Vitol LNGC DES",
            "Vitol LNGC DES",
            "Vitol LNGC FOB - Bintulu",
            "RGT PEGT",
            "VITOL MCN LEG-1",
            "VITOL MCN LEG-1",
            "Vitol MOC",
            "Vitol MOC",
            "PEGT-Tango",
            "RGT PEGT",
            "RGT PEGT",
            "RGT PEGT",
            "RGT PEGT",
            "VITOL MCN LEG-1",
            "BP MCN FOB ",
            "SZG DUA LT",
            "SZG DNC Deferment",
            "SKE PLL",
            "SKE PLC",
            "SHLNG-FOB",
            "SHLNG-DES-RV",
            "SHLNG-DES-YGS",
            "SHLNG-DES-YGS",
            "SBG Hibiki",
            "SBG",
            "SKE PLL",
            "SBG SATU",
            "RWE Package B",
            "PTT",
            "PTT",
            "CNOOC-MCN-FOB",
            "CNOOC MCN-DES",
            "OG Complex",
            "KOGAS DES",
            "KOGAS DES",
            "SBG",
            "SZG DNC",
            "SKE PLL",
            "PEI SPA 1 - Bintulu",
            "SCG DNC",
            "SCG DNC",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "SKE PLL",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "PEI SPA 2 - Canada",
            "SZG DNC Deferment",
            "PEI SPA 2 - Canada",
            "PEI SPA 2 - Canada",
            "S-Oil DES",
            "Shell MCN",
            "EDFT CN (novated to JERAGM)",
            "SHG-Lagenda1&2",
            "2023-PFLNG2_20(PLL)",
            "2023-GLNGT1_17(PLL)_Mit(PET)",
            "2023-GLNGT2_22(PLL) ",
            "2023-GLNGT2_19(PLL).",
            "2023-PL9SB_47(PLL)",
            "2023-PFLNG2(PLL)_10",
            "2023-PFLNG2(PLL)_14",
            "2023-PFLNG1_9(PLL)",
            "2023-PL9SB_52(PLL)",
            "2023-PL9SB_32(PLL)",
            "2023-GLNGT2(PLL)_12",
            "2023-PFLNG2_15(PLL)",
            "2023-PL9SB_40(PLL)",
            "2023-GLNGT1_11(PLL)",
            "Trafi Train 9",
            "Trafi Train 9",
            "Glencore Set 1",
            "BP MCN FOB ",
            "2023-MLNGExcess_01(PLL)",
            "BP MCN FOB ",
            "2023-SPOT06(PLL)",
            "2024-SPOT05(PLL)",
            "2023-PFLNG2_21",
            "2024-PFLNG2_3(PLL)",
            "2024-PFLNG2_6(PLL)",
            "2024-GLNGT1_7(PLL)_Mit(PET)",
            "2024-PFLNG2_4(PLL)",
            "2024-PFLNG2_5(PLL)",
            "2023-PFLNG1_16(PLL)",
            "2023-PFLNG2_19(PLL)",
            "2024-SPOT025(PLL)",
            "2023-SPOT07(PLL)",
            "2024-SPOT04(PLL)",
            "2023-CSPA Opt_09B(PLL)",
            "2023-CSPA Opt_07A(PLL)",
            "2023-CSPA Opt_08(PLL)",
            "2023-GLNGT2_20(PLL)",
            "2024-SPOT02(PLL)",
            "2024-SPOT07(PLL)",
            "2024-SPOT06(PLL)",
            "2024-SPOT08(PLL)",
            "Uniper Swap Leg 1 2024-25",
            "Uniper Swap Leg 1 2024-25",
            "OG JLC",
            "GSETS SPA 2",
            "GSETS SPA 2",
            "GSETS SPA 1",
            "MLNG 3 GC STQ ",
            "MLNG 3 GC STQ ",
            "MLNG 3 GC STQ ",
            "TCEL SPA",
            "TCEL SPA",
            "HKE SATU",
            "Mecuria Even Month F1",
            "Glencore Set 2",
            "Glencore Set 1",
            "Gunvor PFLNG",
            "Trafi CSPA 12.1 Brent",
            "Trafi CSPA 12.1 Brent",
            "Trafi CSPA 12 Brent",
            "MLNG 3 GC STQ ",
            "SHG-Lagenda3",
            "Mecuria Odd Month F1",
            "HKE SATU",
            "HRE SATU",
            "HRE SATU",
            "Mercuria Sabine COPA",
            "PGN (Arun)",
            "SSB-Canada",
            "SSB-FOB",
            "SSB-FOB",
            "JERAGM PLL",
            "Mercuria F2",
            "Dragon",
            "KOGAS IGT Tranche 3",
            "KOGAS IGT Tranche 3",
            "KOGAS IGT Tranche 2",
            "KOGAS IGT Tranche 2",
            "KOGAS IGT Tranche 1",
            "KOGAS IGT Tranche 1",
            "HRE",
            "HRE",
            "HRE SATU",
            "HRE SATU",
            "HRE SATU",
            "ENEOS PLL (Miracle)",
            "2024-SPOT03(PLL)",
            "spot",
            "JOVO-NSPA",
            "ENEOS DNC",
            "THG IND",
            "CDE PLL CSPA",
            "HRG SATU",
            "HRG SATU",
            "PCHK HOA-2",
            "PCHK HOA-2",
            "PCHK HOA-2",
            "CDE PLL CSPA",
            "PCHK HOA-3",
            "JAPEX CSPA",
            "JERA COMPLEX",
            "JERA SATU",
            "JERA MCN",
            "JERA MCN",
            "JERA MCN",
            "PCHK HOA-3",
            "JOVO-ARSPA",
            "TG DNC",
            "SZG DUA LT",
            "SZG DNC",
            "SZG DNC Deferment",
            "SZG DNC Deferment",
            "SCG DNC",
            "SCG DNC",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "S-Oil DES",
            "TG SATU NEW",
            "S-Oil DES",
            "TG SATU NEW",
            "THG PF",
            "TG SATU NEW",
            "RGT PEGT",
            "RGT PEGT",
            "RGT PEGT",
            "RGT GLNG",
            "RGT GLNG",
            "THG LNGC",
            "THG LNGC",
            "TG SATU NEW",
            "THG PF",
            "THG Bintulu 2",
            "THG Bintulu 2",
            "THG Bintulu 2",
            "THG IND",
            "THG IND",
            "THE DNC",
            "TG SATU NEW",
            "PEI SPA 2 - Canada",
            "PEI SPA 2 - Canada",
            "SHLNG-DES-RV",
            "PEI SPA 1 - Bintulu",
            "JOVO-NSPA",
            "JOVO-ARSPA",
            "JERA MCN",
            "JERA MCN",
            "JERA MCN",
            "JERA SATU",
            "JERA COMPLEX",
            "ENEOS DNC",
            "JAPEX CSPA",
            "PCHK HOA-3",
            "PCHK HOA-2",
            "PCHK HOA-2",
            "PCHK HOA-2",
            "HRG SATU",
            "HRG SATU",
            "CDE PLL CSPA",
            "PCHK HOA-3",
            "PEI SPA 2 - Canada",
            "ENEOS DNC",
            "KOGAS DES",
            "SKE PLL",
            "SKE PLL",
            "SKE PLL",
            "SKE PLL",
            "SKE PLC",
            "SHLNG-FOB",
            "RGT PEGT",
            "ENEOS PLL (Miracle)",
            "SHLNG-DES-YGS",
            "SBG Hibiki",
            "SBG",
            "SBG SATU",
            "SBG",
            "PTT",
            "PTT",
            "KOGAS DES",
            "SHLNG-DES-YGS",
            "RGT PEGT",
            "HKE SATU",
            "PEGT-Tango",
            "Trafi Train 9",
            "Trafi Train 9",
            "Glencore Set 1",
            "BP MCN FOB ",
            "BP MCN FOB ",
            "Uniper Swap Leg 1 2024-25",
            "Uniper Swap Leg 1 2024-25",
            "CDE PLL  ",
            "OG JLC",
            "PGN (Arun)",
            "SSB-Canada",
            "SSB-FOB",
            "SSB-FOB",
            "JERAGM PLL",
            "Dragon",
            "KOGAS IGT Tranche 3",
            "Mercuria Sabine COPA",
            "KOGAS IGT Tranche 3",
            "CDE PLL  ",
            "CDE PLL  ",
            "spot",
            "2024-SPOT03(PLL)",
            "2024-PFLNG2_3(PLL)",
            "2024-PFLNG2_6(PLL)",
            "2024-GLNGT1_7(PLL)_Mit(PET)",
            "2024-PFLNG2_4(PLL)",
            "2024-PFLNG2_5(PLL)",
            "CDE PLL  ",
            "2024-SPOT08(PLL)",
            "2024-SPOT02(PLL)",
            "2024-SPOT07(PLL)",
            "2024-SPOT06(PLL)",
            "2024-SPOT05(PLL)",
            "2024-SPOT025(PLL)",
            "ENEOS PLL ",
            "ENEOS PLL ",
            "2024-SPOT04(PLL)",
            "RGT PEGT",
            "KOGAS IGT Tranche 2",
            "KOGAS IGT Tranche 1",
            "EDFT CN (novated to JERAGM)",
            "Shell MCN",
            "BP MCN FOB ",
            "BP MCN DES",
            "BP MCN DES",
            "KOMIPO",
            "Vitol LNGC DES",
            "Mecuria Odd Month F1",
            "Vitol LNGC DES",
            "Vitol LNGC DES",
            "Vitol LNGC FOB - Bintulu",
            "VITOL MCN LEG-1",
            "VITOL MCN LEG-1",
            "VITOL MCN LEG-1",
            "Vitol MOC",
            "Vitol MOC",
            "Vitol LNGC DES",
            "KOGAS IGT Tranche 2",
            "SHG-Lagenda1&2",
            "Trafi CSPA 12.1 Brent",
            "KOGAS IGT Tranche 1",
            "HRE",
            "HRE",
            "HRE SATU",
            "HRE SATU",
            "HRE SATU",
            "HKE SATU",
            "SHG-Lagenda3",
            "GSETS SPA 2",
            "GSETS SPA 1",
            "MLNG 3 GC STQ ",
            "MLNG 3 GC STQ ",
            "MLNG 3 GC STQ ",
            "TCEL SPA",
            "TCEL SPA",
            "Gunvor PFLNG",
            "GSETS SPA 2",
            "CDE PLL CSPA"
        ],
        "contract no": [
            "ENEOS DNC Deferment",
            "RGT GLNG - 2",
            "RGT GLNG - 1",
            "THG LNGC CA volume",
            "THG LNGC T9 volume",
            "THG PF BACQ PR2022-26",
            "THG PF Optional Volume PR2022-26",
            "THG Bintulu 2 BACQ",
            "THG Bintulu 2 Optional Volume",
            "RGT BLNG",
            "THG Bintulu 2 BACQ AAY",
            "THG Bintulu 1 Optional Volume",
            "THG IND",
            "THE DNC PR2021-25",
            "TG SATU NEW - FOB JLC",
            "TG SATU NEW - FOB BACQ & STQ",
            "TG SATU NEW - DES JLC",
            "TG SATU NEW - DES BACQ",
            "TG SATU NEW - DES STQ",
            "THG Bintulu 1 BACQ (AAY with no additional cargo)",
            "TG DNC",
            "RGT PEGT BP",
            "RGT PEGT Uniper Swap",
            "BP MCN DES UQT Summer",
            "BP MCN DES",
            "KOMIPO",
            "Vitol LNGC DES -2",
            "Vitol LNGC DES -1 AVO Winter",
            "Vitol LNGC DES -1 AVO Summer",
            "Vitol LNGC DES -1",
            "Vitol LNGC FOB - Bintulu",
            "RGT PEGT VG",
            "VITOL LEG-2 DES",
            "VITOL LEG-1 DES",
            "Vitol MOC Option Year Option Volume Brent",
            "Vitol MOC Option Year Brent",
            "PEGT-Tango",
            "RGT PEGT PLL Portfolio",
            "RGT PEGT Train 9 - 2",
            "RGT PEGT Train 9 - 1",
            "RGT PEGT Uniper Swap Optional Year Price different",
            "VITOL LEG-1 FOB",
            "BP MCN FOB ",
            "SZG DUA LT",
            "SZG DNC Deferment",
            "SKE PLL BACQ",
            "SKE PLC",
            "SHLNG-FOB",
            "SHLNG-DES-RV",
            "SHLNG-DES-DOTS",
            "SHLNG-DES-YGS",
            "SBG Hibiki",
            "SBG Repackaging",
            "SKE PLL Optional Volume",
            "SBG SATU PR2023-28",
            "RWE Package B-3",
            "PTT PR2027-31",
            "PTT PR2022-26",
            "CNOOC-MCN-FOB",
            "CNOOC MCN-DES",
            "OG Complex",
            "KOGAS DES - UQT PR2023-27",
            "KOGAS DES - BACQ PR2023-27",
            "SBG Deferment",
            "SZG DNC PR2021",
            "SKE Long Term Deal A",
            "PEI SPA 1 - Bintulu",
            "SCG DNC PR2025-27",
            "SCG DNC",
            "S-Oil UQT PR2028-32",
            "S-Oil OAQ  PR2028-32",
            "S-Oil BACQ PR2028-32",
            "S-Oil OAQ  Q1 2028",
            "S-Oil BACQ Q1 2028",
            "S-Oil UQT PR2023-27",
            "SKE Long Term Deal B",
            "S-Oil OAQ  PR2023-27",
            "S-Oil OAQ  Q1 2023",
            "S-Oil BACQ Q1 2023",
            "S-Oil OAQ ",
            "S-Oil BACQ",
            "PEI SPA 2 - Canada PR2029-33",
            "SZG DNC Deferment PR2021",
            "PEI SPA 2 - Canada volume",
            "PEI SPA 2 - T9 volume",
            "S-Oil BACQ PR2023-27",
            "Shell MCN",
            "EDFT CN (novated to JERAGM)",
            "SHG-Lagenda1&2",
            "2023-PFLNG2_20(PLL)",
            "2023-GLNGT1_17(PLL)_Mit(PET)",
            "2023-GLNGT2_22(PLL) ",
            "2023-GLNGT2_19(PLL).",
            "2023-PL9SB_47(PLL)",
            "2023-PFLNG2(PLL)_10",
            "2023-PFLNG2(PLL)_14",
            "2023-PFLNG1_9(PLL)",
            "2023-PL9SB_52(PLL)",
            "2023-PL9SB_32(PLL)",
            "2023-GLNGT2(PLL)_12",
            "2023-PFLNG2_15(PLL)",
            "2023-PL9SB_40(PLL)",
            "2023-GLNGT1_11(PLL)",
            "Trafi Train 9B",
            "Trafi Train 9A",
            "Glencore Set 1 Deferred",
            "BP FOB_deferred",
            "2023-MLNGExcess_01(PLL)",
            "BP FOB_ConvertFOB_Deferred",
            "2023-SPOT06(PLL)",
            "2024-SPOT05(PLL)",
            "2023-PFLNG2_21",
            "2024-PFLNG2_3(PLL)",
            "2024-PFLNG2_6(PLL)",
            "2024-GLNGT1_7(PLL)_Mit(PET)",
            "2024-PFLNG2_4(PLL)",
            "2024-PFLNG2_5(PLL)",
            "2023-PFLNG1_16(PLL)",
            "2023-PFLNG2_19(PLL)",
            "2024-SPOT025(PLL)",
            "2023-SPOT07(PLL)",
            "2024-SPOT04(PLL)",
            "2023-CSPA Opt_09B(PLL)",
            "2023-CSPA Opt_07A(PLL)",
            "2023-CSPA Opt_08(PLL)",
            "2023-GLNGT2_20(PLL)",
            "2024-SPOT02(PLL)",
            "2024-SPOT07(PLL)",
            "2024-SPOT06(PLL)",
            "2024-SPOT08(PLL)",
            "Uniper Swap Leg 1 2024 optionality",
            "Uniper Swap Leg 1 2024-25",
            "OG JLC",
            "GSETS SPA 2 - winter",
            "GSETS SPA 2 - summer",
            "GSETS SPA 1",
            "MLNG 3 GC STQ  FOB",
            "MLNG 3 GC STQ DES Deferment",
            "MLNG 3 GC STQ DES",
            "TCEL SPA UQT",
            "TCEL SPA BACQ",
            "HKE SATU BACQ PR2023-27",
            "Mecuria Even Month F1",
            "Glencore Set 2",
            "Glencore Set 1",
            "Gunvor PFLNG",
            "Trafi CSPA 12.1 Brent - B",
            "Trafi CSPA 12.1 Brent - A",
            "Trafi CSPA 12 Brent - A",
            "MLNG 3 GC BACQ",
            "SHG-Lagenda3",
            "Mecuria Odd Month F1",
            "HKE SATU UQT PR2023-27",
            "HRE SATU - BACQ PR2023-27",
            "HRE SATU - Spot buy",
            "Mercuria Sabine COPA",
            "PGN (Arun)",
            "SSB-Canada",
            "SSB-FOB-2",
            "SSB-FOB-1",
            "JERAGM PLL",
            "Mercuria F2",
            "Dragon",
            "KOGAS IGT Tranche 3 PR2032-35",
            "KOGAS IGT Tranche 3",
            "KOGAS IGT Tranche 2 PR2031-39",
            "KOGAS IGT Tranche 2",
            "KOGAS IGT Tranche 1 PR2030-38",
            "KOGAS IGT Tranche 1",
            "HRE - CY2023-2027 - BACQ - DES - B",
            "HRE - CY2023-2027 - BACQ - DES - A",
            "HRE SATU - UQT PR2023-27 -2",
            "HRE SATU - UQT PR2023-27 -1",
            "HRE SATU - UQT - 1",
            "ENEOS PLL (Miracle)",
            "2024-SPOT03(PLL)",
            "spot",
            "JOVO-NSPA",
            "ENEOS DNC PR2020",
            "THG IND PR2024-26",
            "CDE PLL CSPA - BACQ Upward revision",
            "HRG SATU PR2021-25",
            "HRG SATU Extension 2026-30",
            "PCHK HOA-2 DES",
            "PCHK HOA-2 FOB LJ",
            "PCHK HOA-2 FOB LAM",
            "CDE PLL CSPA",
            "PCHK HOA-3-CA volume",
            "JAPEX CSPA 2023-25",
            "JERA COMPLEX",
            "JERA SATU DES BACQ",
            "JERA MCN DES ",
            "JERA MCN DES STQ",
            "JERA MCN FOB",
            "PCHK HOA-3-PLL volume",
            "JOVO-ARSPA",
            "TG DNC",
            "SZG DUA LT",
            "SZG DNC PR2021",
            "SZG DNC Deferment PR2021",
            "SZG DNC Deferment",
            "SCG DNC PR2025-27",
            "SCG DNC",
            "S-Oil OAQ  Q1 2028",
            "S-Oil OAQ  PR2028-32",
            "S-Oil BACQ PR2028-32",
            "S-Oil BACQ Q1 2028",
            "S-Oil UQT PR2023-27",
            "S-Oil OAQ  PR2023-27",
            "S-Oil BACQ PR2023-27",
            "TG SATU NEW - DES STQ",
            "S-Oil UQT PR2028-32",
            "TG SATU NEW - DES BACQ",
            "THG PF Optional Volume PR2022-26",
            "TG SATU NEW - FOB BACQ & STQ",
            "RGT PEGT Uniper Swap",
            "RGT PEGT VG",
            "RGT PEGT BP",
            "RGT GLNG - 2",
            "RGT GLNG - 1",
            "THG LNGC CA volume",
            "THG LNGC T9 volume",
            "TG SATU NEW - DES JLC",
            "THG PF BACQ PR2022-26",
            "THG Bintulu 2 BACQ",
            "THG Bintulu 2 Optional Volume",
            "THG Bintulu 2 BACQ AAY",
            "THG IND PR2024-26",
            "THG IND",
            "THE DNC PR2021-25",
            "TG SATU NEW - FOB JLC",
            "PEI SPA 2 - Canada PR2029-33",
            "PEI SPA 2 - Canada volume",
            "SHLNG-DES-RV",
            "PEI SPA 1 - Bintulu",
            "JOVO-NSPA",
            "JOVO-ARSPA",
            "JERA MCN FOB",
            "JERA MCN DES STQ",
            "JERA MCN DES ",
            "JERA SATU DES BACQ",
            "JERA COMPLEX",
            "ENEOS DNC PR2020",
            "JAPEX CSPA 2023-25",
            "PCHK HOA-3-PLL volume",
            "PCHK HOA-2 FOB LAM",
            "PCHK HOA-2 FOB LJ",
            "PCHK HOA-2 DES",
            "HRG SATU Extension 2026-30",
            "HRG SATU PR2021-25",
            "CDE PLL CSPA - BACQ Upward revision",
            "PCHK HOA-3-CA volume",
            "PEI SPA 2 - T9 volume",
            "ENEOS DNC Deferment",
            "KOGAS DES - BACQ PR2023-27",
            "SKE Long Term Deal B",
            "SKE Long Term Deal A",
            "SKE PLL Optional Volume",
            "SKE PLL BACQ",
            "SKE PLC",
            "SHLNG-FOB",
            "RGT PEGT Uniper Swap Optional Year Price different",
            "ENEOS PLL (Miracle)",
            "SHLNG-DES-DOTS",
            "SBG Hibiki",
            "SBG Repackaging",
            "SBG SATU PR2023-28",
            "SBG Deferment",
            "PTT PR2027-31",
            "PTT PR2022-26",
            "KOGAS DES - UQT PR2023-27",
            "SHLNG-DES-YGS",
            "RGT PEGT Train 9 - 2",
            "HKE SATU UQT PR2023-27",
            "PEGT-Tango",
            "Trafi Train 9B",
            "Trafi Train 9A",
            "Glencore Set 1 Deferred",
            "BP FOB_deferred",
            "BP FOB_ConvertFOB_Deferred",
            "Uniper Swap Leg 1 2024 optionality",
            "Uniper Swap Leg 1 2024-25",
            "S1-41-A",
            "OG JLC",
            "PGN (Arun)",
            "SSB-Canada",
            "SSB-FOB-2",
            "SSB-FOB-1",
            "JERAGM PLL",
            "Dragon",
            "KOGAS IGT Tranche 3 PR2032-35",
            "Mercuria Sabine COPA",
            "KOGAS IGT Tranche 3",
            "S1-41-B",
            "S1-41-D",
            "spot",
            "2024-SPOT03(PLL)",
            "2024-PFLNG2_3(PLL)",
            "2024-PFLNG2_6(PLL)",
            "2024-GLNGT1_7(PLL)_Mit(PET)",
            "2024-PFLNG2_4(PLL)",
            "2024-PFLNG2_5(PLL)",
            "S1-41-C",
            "2024-SPOT08(PLL)",
            "2024-SPOT02(PLL)",
            "2024-SPOT07(PLL)",
            "2024-SPOT06(PLL)",
            "2024-SPOT05(PLL)",
            "2024-SPOT025(PLL)",
            "S1-42-B",
            "S1-42-A",
            "2024-SPOT04(PLL)",
            "RGT PEGT PLL Portfolio",
            "KOGAS IGT Tranche 2 PR2031-39",
            "KOGAS IGT Tranche 1 PR2030-38",
            "EDFT CN (novated to JERAGM)",
            "Shell MCN",
            "BP MCN FOB ",
            "BP MCN DES UQT Summer",
            "BP MCN DES",
            "KOMIPO",
            "Vitol LNGC DES -2",
            "Mecuria Odd Month F1",
            "Vitol LNGC DES -1 AVO Winter",
            "Vitol LNGC DES -1",
            "Vitol LNGC FOB - Bintulu",
            "VITOL LEG-2 DES",
            "VITOL LEG-1 FOB",
            "VITOL LEG-1 DES",
            "Vitol MOC Option Year Option Volume Brent",
            "Vitol MOC Option Year Brent",
            "Vitol LNGC DES -1 AVO Summer",
            "KOGAS IGT Tranche 2",
            "SHG-Lagenda1&2",
            "Trafi CSPA 12.1 Brent - B",
            "KOGAS IGT Tranche 1",
            "HRE - CY2023-2027 - BACQ - DES - B",
            "HRE - CY2023-2027 - BACQ - DES - A",
            "HRE SATU - UQT PR2023-27 -2",
            "HRE SATU - UQT PR2023-27 -1",
            "HRE SATU - BACQ PR2023-27",
            "HKE SATU BACQ PR2023-27",
            "SHG-Lagenda3",
            "GSETS SPA 2 - winter",
            "GSETS SPA 1",
            "MLNG 3 GC STQ  FOB",
            "MLNG 3 GC BACQ",
            "MLNG 3 GC STQ DES",
            "TCEL SPA UQT",
            "TCEL SPA BACQ",
            "Gunvor PFLNG",
            "GSETS SPA 2 - summer",
            "CDE PLL CSPA"
        ],
        "contract_no_preferred": [
            "ENEOS DNC Deferment",
            "RGT GLNG - 2",
            "RGT GLNG - 1",
            "THG LNGC CA volume",
            "THG LNGC T9 volume",
            "THG PF BACQ PR2022-26",
            "THG PF Optional Volume PR2022-26",
            "THG Bintulu 2 BACQ",
            "THG Bintulu 2 Optional Volume",
            "RGT BLNG",
            "THG Bintulu 2 BACQ AAY",
            "THG Bintulu 1 Optional Volume",
            "THG IND",
            "THE DNC PR2021-25",
            "TG SATU NEW - FOB JLC",
            "TG SATU NEW - FOB BACQ & STQ",
            "TG SATU NEW - DES JLC",
            "TG SATU NEW - DES BACQ",
            "TG SATU NEW - DES STQ",
            "THG Bintulu 1 BACQ (AAY with no additional cargo)",
            "TG DNC",
            "RGT PEGT BP",
            "RGT PEGT Uniper Swap",
            "BP MCN DES UQT Summer",
            "BP MCN DES",
            "KOMIPO",
            "Vitol LNGC DES -2",
            "Vitol LNGC DES -1 AVO Winter",
            "Vitol LNGC DES -1 AVO Summer",
            "Vitol LNGC DES -1",
            "Vitol LNGC FOB - Bintulu",
            "RGT PEGT VG",
            "VITOL LEG-2 DES",
            "VITOL LEG-1 DES",
            "Vitol MOC Option Year Option Volume Brent",
            "Vitol MOC Option Year Brent",
            "PEGT-Tango",
            "RGT PEGT PLL Portfolio",
            "RGT PEGT Train 9 - 2",
            "RGT PEGT Train 9 - 1",
            "RGT PEGT Uniper Swap Optional Year Price different",
            "VITOL LEG-1 FOB",
            "BP MCN FOB ",
            "SZG DUA LT",
            "SZG DNC Deferment",
            "SKE PLL BACQ",
            "SKE PLC",
            "SHLNG-FOB",
            "SHLNG-DES-RV",
            "SHLNG-DES-DOTS",
            "SHLNG-DES-YGS",
            "SBG Hibiki",
            "SBG Repackaging",
            "SKE PLL Optional Volume",
            "SBG SATU PR2023-28",
            "RWE Package B-3",
            "PTT PR2027-31",
            "PTT PR2022-26",
            "CNOOC-MCN-FOB",
            "CNOOC MCN-DES",
            "OG Complex",
            "KOGAS DES - UQT PR2023-27",
            "KOGAS DES - BACQ PR2023-27",
            "SBG Deferment",
            "SZG DNC PR2021",
            "SKE Long Term Deal A",
            "PEI SPA 1 - Bintulu",
            "SCG DNC PR2025-27",
            "SCG DNC",
            "S-Oil UQT PR2028-32",
            "S-Oil OAQ  PR2028-32",
            "S-Oil BACQ PR2028-32",
            "S-Oil OAQ  Q1 2028",
            "S-Oil BACQ Q1 2028",
            "S-Oil UQT PR2023-27",
            "SKE Long Term Deal B",
            "S-Oil OAQ  PR2023-27",
            "S-Oil OAQ  Q1 2023",
            "S-Oil BACQ Q1 2023",
            "S-Oil OAQ ",
            "S-Oil BACQ",
            "PEI SPA 2 - Canada PR2029-33",
            "SZG DNC Deferment PR2021",
            "PEI SPA 2 - Canada volume",
            "PEI SPA 2 - T9 volume",
            "S-Oil BACQ PR2023-27",
            "Shell MCN",
            "EDFT CN (novated to JERAGM)",
            "SHG-Lagenda1&2",
            "2023-PFLNG2_20(PLL)",
            "2023-GLNGT1_17(PLL)_Mit(PET)",
            "2023-GLNGT2_22(PLL) ",
            "2023-GLNGT2_19(PLL).",
            "2023-PL9SB_47(PLL)",
            "2023-PFLNG2(PLL)_10",
            "2023-PFLNG2(PLL)_14",
            "2023-PFLNG1_9(PLL)",
            "2023-PL9SB_52(PLL)",
            "2023-PL9SB_32(PLL)",
            "2023-GLNGT2(PLL)_12",
            "2023-PFLNG2_15(PLL)",
            "2023-PL9SB_40(PLL)",
            "2023-GLNGT1_11(PLL)",
            "Trafi Train 9B",
            "Trafi Train 9A",
            "Glencore Set 1 Deferred",
            "BP FOB_deferred",
            "2023-MLNGExcess_01(PLL)",
            "BP FOB_ConvertFOB_Deferred",
            "2023-SPOT06(PLL)",
            "2024-SPOT05(PLL)",
            "2023-PFLNG2_21",
            "2024-PFLNG2_3(PLL)",
            "2024-PFLNG2_6(PLL)",
            "2024-GLNGT1_7(PLL)_Mit(PET)",
            "2024-PFLNG2_4(PLL)",
            "2024-PFLNG2_5(PLL)",
            "2023-PFLNG1_16(PLL)",
            "2023-PFLNG2_19(PLL)",
            "2024-SPOT025(PLL)",
            "2023-SPOT07(PLL)",
            "2024-SPOT04(PLL)",
            "2023-CSPA Opt_09B(PLL)",
            "2023-CSPA Opt_07A(PLL)",
            "2023-CSPA Opt_08(PLL)",
            "2023-GLNGT2_20(PLL)",
            "2024-SPOT02(PLL)",
            "2024-SPOT07(PLL)",
            "2024-SPOT06(PLL)",
            "2024-SPOT08(PLL)",
            "Uniper Swap Leg 1 2024 optionality",
            "Uniper Swap Leg 1 2024-25",
            "OG JLC",
            "GSETS SPA 2 - winter",
            "GSETS SPA 2 - summer",
            "GSETS SPA 1",
            "MLNG 3 GC STQ  FOB",
            "MLNG 3 GC STQ DES Deferment",
            "MLNG 3 GC STQ DES",
            "TCEL SPA UQT",
            "TCEL SPA BACQ",
            "HKE SATU BACQ PR2023-27",
            "Mecuria Even Month F1",
            "Glencore Set 2",
            "Glencore Set 1",
            "Gunvor PFLNG",
            "Trafi CSPA 12.1 Brent - B",
            "Trafi CSPA 12.1 Brent - A",
            "Trafi CSPA 12 Brent - A",
            "MLNG 3 GC BACQ",
            "SHG-Lagenda3",
            "Mecuria Odd Month F1",
            "HKE SATU UQT PR2023-27",
            "HRE SATU - BACQ PR2023-27",
            "HRE SATU - Spot buy",
            "Mercuria Sabine COPA",
            "PGN (Arun)",
            "SSB-Canada",
            "SSB-FOB-2",
            "SSB-FOB-1",
            "JERAGM PLL",
            "Mercuria F2",
            "Dragon",
            "KOGAS IGT Tranche 3 PR2032-35",
            "KOGAS IGT Tranche 3",
            "KOGAS IGT Tranche 2 PR2031-39",
            "KOGAS IGT Tranche 2",
            "KOGAS IGT Tranche 1 PR2030-38",
            "KOGAS IGT Tranche 1",
            "HRE - CY2023-2027 - BACQ - DES - B",
            "HRE - CY2023-2027 - BACQ - DES - A",
            "HRE SATU - UQT PR2023-27 -2",
            "HRE SATU - UQT PR2023-27 -1",
            "HRE SATU - UQT - 1",
            "ENEOS PLL (Miracle)",
            "2024-SPOT03(PLL)",
            "spot",
            "JOVO-NSPA",
            "ENEOS DNC PR2020",
            "THG IND PR2024-26",
            "CDE PLL CSPA - BACQ Upward revision",
            "HRG SATU PR2021-25",
            "HRG SATU Extension 2026-30",
            "PCHK HOA-2 DES",
            "PCHK HOA-2 FOB LJ",
            "PCHK HOA-2 FOB LAM",
            "CDE PLL CSPA",
            "PCHK HOA-3-CA volume",
            "JAPEX CSPA 2023-25",
            "JERA COMPLEX",
            "JERA SATU DES BACQ",
            "JERA MCN DES ",
            "JERA MCN DES STQ",
            "JERA MCN FOB",
            "PCHK HOA-3-PLL volume",
            "JOVO-ARSPA",
            "TG DNC",
            "SZG DUA LT",
            "SZG DNC PR2021",
            "SZG DNC Deferment PR2021",
            "SZG DNC Deferment",
            "SCG DNC PR2025-27",
            "SCG DNC",
            "S-Oil OAQ  Q1 2028",
            "S-Oil OAQ  PR2028-32",
            "S-Oil BACQ PR2028-32",
            "S-Oil BACQ Q1 2028",
            "S-Oil UQT PR2023-27",
            "S-Oil OAQ  PR2023-27",
            "S-Oil BACQ PR2023-27",
            "TG SATU NEW - DES STQ",
            "S-Oil UQT PR2028-32",
            "TG SATU NEW - DES BACQ",
            "THG PF Optional Volume PR2022-26",
            "TG SATU NEW - FOB BACQ & STQ",
            "RGT PEGT Uniper Swap",
            "RGT PEGT VG",
            "RGT PEGT BP",
            "RGT GLNG - 2",
            "RGT GLNG - 1",
            "THG LNGC CA volume",
            "THG LNGC T9 volume",
            "TG SATU NEW - DES JLC",
            "THG PF BACQ PR2022-26",
            "THG Bintulu 2 BACQ",
            "THG Bintulu 2 Optional Volume",
            "THG Bintulu 2 BACQ AAY",
            "THG IND PR2024-26",
            "THG IND",
            "THE DNC PR2021-25",
            "TG SATU NEW - FOB JLC",
            "PEI SPA 2 - Canada PR2029-33",
            "PEI SPA 2 - Canada volume",
            "SHLNG-DES-RV",
            "PEI SPA 1 - Bintulu",
            "JOVO-NSPA",
            "JOVO-ARSPA",
            "JERA MCN FOB",
            "JERA MCN DES STQ",
            "JERA MCN DES ",
            "JERA SATU DES BACQ",
            "JERA COMPLEX",
            "ENEOS DNC PR2020",
            "JAPEX CSPA 2023-25",
            "PCHK HOA-3-PLL volume",
            "PCHK HOA-2 FOB LAM",
            "PCHK HOA-2 FOB LJ",
            "PCHK HOA-2 DES",
            "HRG SATU Extension 2026-30",
            "HRG SATU PR2021-25",
            "CDE PLL CSPA - BACQ Upward revision",
            "PCHK HOA-3-CA volume",
            "PEI SPA 2 - T9 volume",
            "ENEOS DNC Deferment",
            "KOGAS DES - BACQ PR2023-27",
            "SKE Long Term Deal B",
            "SKE Long Term Deal A",
            "SKE PLL Optional Volume",
            "SKE PLL BACQ",
            "SKE PLC",
            "SHLNG-FOB",
            "RGT PEGT Uniper Swap Optional Year Price different",
            "ENEOS PLL (Miracle)",
            "SHLNG-DES-DOTS",
            "SBG Hibiki",
            "SBG Repackaging",
            "SBG SATU PR2023-28",
            "SBG Deferment",
            "PTT PR2027-31",
            "PTT PR2022-26",
            "KOGAS DES - UQT PR2023-27",
            "SHLNG-DES-YGS",
            "RGT PEGT Train 9 - 2",
            "HKE SATU UQT PR2023-27",
            "PEGT-Tango",
            "Trafi Train 9B",
            "Trafi Train 9A",
            "Glencore Set 1 Deferred",
            "BP FOB_deferred",
            "BP FOB_ConvertFOB_Deferred",
            "Uniper Swap Leg 1 2024 optionality",
            "Uniper Swap Leg 1 2024-25",
            "S1-41-A",
            "OG JLC",
            "PGN (Arun)",
            "SSB-Canada",
            "SSB-FOB-2",
            "SSB-FOB-1",
            "JERAGM PLL",
            "Dragon",
            "KOGAS IGT Tranche 3 PR2032-35",
            "Mercuria Sabine COPA",
            "KOGAS IGT Tranche 3",
            "S1-41-B",
            "S1-41-D",
            "spot",
            "2024-SPOT03(PLL)",
            "2024-PFLNG2_3(PLL)",
            "2024-PFLNG2_6(PLL)",
            "2024-GLNGT1_7(PLL)_Mit(PET)",
            "2024-PFLNG2_4(PLL)",
            "2024-PFLNG2_5(PLL)",
            "S1-41-C",
            "2024-SPOT08(PLL)",
            "2024-SPOT02(PLL)",
            "2024-SPOT07(PLL)",
            "2024-SPOT06(PLL)",
            "2024-SPOT05(PLL)",
            "2024-SPOT025(PLL)",
            "S1-42-B",
            "S1-42-A",
            "2024-SPOT04(PLL)",
            "RGT PEGT PLL Portfolio",
            "KOGAS IGT Tranche 2 PR2031-39",
            "KOGAS IGT Tranche 1 PR2030-38",
            "EDFT CN (novated to JERAGM)",
            "Shell MCN",
            "BP MCN FOB ",
            "BP MCN DES UQT Summer",
            "BP MCN DES",
            "KOMIPO",
            "Vitol LNGC DES -2",
            "Mecuria Odd Month F1",
            "Vitol LNGC DES -1 AVO Winter",
            "Vitol LNGC DES -1",
            "Vitol LNGC FOB - Bintulu",
            "VITOL LEG-2 DES",
            "VITOL LEG-1 FOB",
            "VITOL LEG-1 DES",
            "Vitol MOC Option Year Option Volume Brent",
            "Vitol MOC Option Year Brent",
            "Vitol LNGC DES -1 AVO Summer",
            "KOGAS IGT Tranche 2",
            "SHG-Lagenda1&2",
            "Trafi CSPA 12.1 Brent - B",
            "KOGAS IGT Tranche 1",
            "HRE - CY2023-2027 - BACQ - DES - B",
            "HRE - CY2023-2027 - BACQ - DES - A",
            "HRE SATU - UQT PR2023-27 -2",
            "HRE SATU - UQT PR2023-27 -1",
            "HRE SATU - BACQ PR2023-27",
            "HKE SATU BACQ PR2023-27",
            "SHG-Lagenda3",
            "GSETS SPA 2 - winter",
            "GSETS SPA 1",
            "MLNG 3 GC STQ  FOB",
            "MLNG 3 GC BACQ",
            "MLNG 3 GC STQ DES",
            "TCEL SPA UQT",
            "TCEL SPA BACQ",
            "Gunvor PFLNG",
            "GSETS SPA 2 - summer",
            "CDE PLL CSPA"
        ],
        "1st_source": [
            "MLNG DUA",
            "GLNG T2",
            "GLNG T1",
            "CANADA",
            "Train 9",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "BLNG",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG TIGA",
            "MLNG DUA",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "MLNG DUA",
            "BPS, FLNG 1, FLNG 2",
            "Uniper-1, FLNG 1, FLNG 2",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "Train 9",
            "CANADA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "Train 9",
            "VG",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "Train 9",
            "FLNG 1, FLNG 2, GLNG T1, GLNG T2, Train 9, CANADA, SERI, ZLNG, Argentina",
            "Train 9",
            "Train 9",
            "Uniper-1, FLNG 1, FLNG 2",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG DUA",
            "MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG SATU",
            "MLNG DUA",
            "MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG DUA",
            "MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "CANADA",
            "MLNG DUA",
            "CANADA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "GLNG",
            "FLNG 2",
            "GLNG",
            "GLNG",
            "Train 9",
            "FLNG 2",
            "FLNG 2",
            "FLNG 1",
            "Train 9",
            "Train 9",
            "GLNG",
            "FLNG 2",
            "Train 9",
            "GLNG",
            "Train 9",
            "Train 9",
            "Train 9",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA",
            "Wheatnell",
            "Bintulu",
            "FLNG 2",
            "FLNG 2",
            "FLNG 2",
            "GLNG",
            "FLNG 2",
            "FLNG 2",
            "FLNG 1",
            "FLNG 2",
            "Bintulu",
            "Wheatsone",
            "Nigeria",
            "Train 9",
            "Train 9",
            "Train 9",
            "GLNG",
            "Gorgon",
            "Bintulu",
            "Bintulu",
            "Train 9",
            "SERI",
            "SERI",
            "Train 9, CANADA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "FLNG 2, Train 9, FLNG 1, GLNG T1, GLNG T2, Canada, BLNG, SERI",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "FLNG 1",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG TIGA",
            "Train 9",
            "FLNG 1",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "Train 9",
            "SERI",
            "Train 9",
            "CANADA",
            "MLNG SATU",
            "Train 9",
            "Train 9, FLNG 1, FLNG 2",
            "FLNG 1, FLNG 2",
            "Dragon_seller1, Dragon_seller2, Dragon_seller3, Dragon_seller4, Dragon_seller5, Dragon_seller6, Dragon_seller7, Dragon_seller8, Dragon_seller9",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "Nigeria",
            "Train 9, FLNG 1, FLNG 2, GLNG",
            "Train 9",
            "MLNG DUA",
            "MLNG TIGA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU",
            "MLNG SATU",
            "Train 9",
            "Train 9",
            "Train 9",
            "MLNG SATU, MLNG DUA",
            "CANADA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU",
            "MLNG DUA",
            "MLNG DUA",
            "MLNG DUA",
            "MLNG DUA",
            "MLNG DUA",
            "MLNG DUA",
            "MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU",
            "Uniper-1, FLNG 1, FLNG 2",
            "VG",
            "BPS, FLNG 1, FLNG 2",
            "GLNG T2",
            "GLNG T1",
            "CANADA",
            "Train 9",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG DUA",
            "MLNG SATU",
            "CANADA",
            "CANADA",
            "MLNG TIGA",
            "MLNG SATU, MLNG DUA",
            "Train 9",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "Train 9",
            "Train 9",
            "Train 9",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "CANADA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG DUA",
            "MLNG TIGA",
            "MLNG DUA",
            "MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG TIGA",
            "MLNG TIGA",
            "Uniper-1, FLNG 1, FLNG 2",
            "MLNG SATU, MLNG DUA",
            "MLNG TIGA",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG TIGA",
            "MLNG TIGA",
            "Train 9",
            "MLNG SATU, MLNG DUA",
            "Train 9",
            "Train 9",
            "Train 9",
            "Train 9",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "SERI",
            "SERI",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "Train 9, CANADA",
            "Train 9",
            "CANADA",
            "MLNG SATU",
            "Train 9",
            "Train 9, FLNG 1, FLNG 2",
            "Dragon_seller1, Dragon_seller2, Dragon_seller3, Dragon_seller4, Dragon_seller5, Dragon_seller6, Dragon_seller7, Dragon_seller8, Dragon_seller9",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "SERI",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "Train 9, FLNG 1, FLNG 2, GLNG",
            "Nigeria",
            "FLNG 2",
            "FLNG 2",
            "GLNG",
            "FLNG 2",
            "FLNG 2",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "Train 9",
            "Gorgon",
            "Bintulu",
            "Bintulu",
            "Bintulu",
            "Bintulu",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "Nigeria",
            "FLNG 1, FLNG 2, GLNG T1, GLNG T2, Train 9, CANADA, SERI, ZLNG, Argentina",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "Train 9",
            "CANADA",
            "FLNG 1",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "Train 9",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Canada",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "Train 9",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG TIGA",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA",
            "FLNG 1",
            "MLNG SATU, MLNG DUA",
            "MLNG SATU, MLNG DUA"
        ],
        "2nd_source": [
            "MLNG SATU, MLNG TIGA, Train 9",
            "nan",
            "nan",
            "Train 9",
            "CANADA",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9, CANADA",
            "MLNG TIGA, Train 9, CANADA",
            "nan",
            "MLNG TIGA, Train 9, CANADA",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "nan",
            "nan",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, GLNG T1, GLNG T2, FLNG 1, FLNG 2, CANADA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "CANADA",
            "CANADA",
            "CANADA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "nan",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "FLNG 1, FLNG 2",
            "nan",
            "nan",
            "nan",
            "nan",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, CANADA",
            "MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, CANADA",
            "MLNG TIGA, GLNG T1, GLNG T2, Train 9",
            "MLNG TIGA, FLNG 1, FLNG 2, GLNG T1, GLNG T2, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG SATU",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "CANADA",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9, FLNG 1, FLNG 2, RGT, Canada, GLNG T1, GLNG T2, BLNG",
            "MLNG TIGA, Train 9",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 2, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "FLNG 1, FLNG 2, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, FLNG 2, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "FLNG 1, FLNG 2, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, FLNG 2, MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG DUA, MLNG TIGA, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "FLNG 1",
            "MLNG TIGA, Train 9",
            "FLNG 1, FLNG 2, GLNG, Train 9",
            "MLNG TIGA, Train 9",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "nan",
            "nan",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "nan",
            "MLNG TIGA, Train 9, FLNG 1, FLNG 2",
            "MLNG TIGA, Train 9, FLNG 1",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 2",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 2",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "nan",
            "nan",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG DUA",
            "nan",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "nan",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "nan",
            "nan",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "CANADA",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9, FLNG 1, GLNG T1, GLNG T2",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "nan",
            "nan",
            "nan",
            "nan",
            "nan",
            "Train 9",
            "CANADA",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9, CANADA",
            "MLNG TIGA, Train 9, CANADA",
            "MLNG TIGA, Train 9, CANADA",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "CANADA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9",
            "CANADA",
            "MLNG SATU, MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU",
            "MLNG SATU",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "nan",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, CANADA",
            "MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2, CANADA",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "nan",
            "MLNG TIGA, Train 9",
            "FLNG 1, FLNG 2",
            "MLNG SATU, MLNG DUA, MLNG TIGA, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG DUA, MLNG TIGA, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "FLNG 1",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "nan",
            "nan",
            "nan",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG DUA",
            "nan",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "nan",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "nan",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "nan",
            "nan",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "nan",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "nan",
            "nan",
            "Train 9, FLNG 1, GLNG, MLNG SATU, MLNG DUA, MLNG TIGA",
            "nan",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG TIGA, Train 9, FLNG 1, FLNG 2, RGT, Canada, GLNG T1, GLNG T2, BLNG",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, GLNG T1, GLNG T2, FLNG 1, FLNG 2, CANADA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 2",
            "CANADA",
            "CANADA",
            "MLNG SATU, MLNG DUA, MLNG TIGA, FLNG 1, FLNG 2, GLNG T1, GLNG T2",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "CANADA",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "nan",
            "nan",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG DUA, MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG SATU, MLNG DUA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9",
            "MLNG SATU, MLNG DUA, MLNG TIGA, Train 9, FLNG 2",
            "MLNG TIGA, Train 9",
            "MLNG TIGA, Train 9"
        ],
        "scenario": [
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "[Base] KPBI_Base 2024-05-07",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV",
            "test run base PV"
        ]
    }